### ISSUE TITLE
IntelliJ IDEA 2023.2 (Ultimate Edition)でSQLリンクアイコンが表示されない

### ISSUE THREAD

**Issue by orimajp** [siosio/DomaSupport#13]
Daoに表示されていたSQLファイルへのリンクアイコンがいつの間にか表示されなくなっているようです。

<img width="425" alt="スクリーンショット 2023-08-05 21 25 38" src="https://github.com/siosio/DomaSupport/assets/7277806/f88d753a-5597-4064-a011-896f25f5a4c3">

環境は以下のとおりです。

Doma Support 1.0.6

IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON

**Comment by drykod** [comment]
![Screenshot_20230810-204852~3](https://github.com/siosio/DomaSupport/assets/274046/feddf5e1-4344-4d74-9e61-bfc4d44a9f9e)
表示されているドットをクリックしてください。

**Comment by drykod** [comment]
PR:
https://github.com/siosio/DomaSupport/pull/14

**Comment by siosio** [comment]
1.0.7で対応しました！ @orimajp 報告ありがとうございます！

https://plugins.jetbrains.com/plugin/7615-doma-support/versions/stable/383061
