### ISSUE TITLE
SQLを利用した挿入・更新・削除メソッドで不適切なエラーが表示される

### ISSUE THREAD

**Issue by tasuku-s** [siosio/DomaSupport#8]
[bbf7521](https://github.com/siosio/DomaSupport/commit/bbf7521352592664886d369042f82d27ef4e1057) で追加されたチェックですが、例えば`@Delete(sqlFile=true)`とした場合にも適用されているようです。  
各アノテーションにおいて、`sqlFile=true`とした場合にはこのチェックを行わないのが適切ではないでしょうか。

**Comment by siosio** [comment]
バグ報告ありがとうございます。対応します。

**Comment by siosio** [comment]
対応しました。

公式サイトからダウンロード可能になるまで少し時間がかかるので、このリンクからダウンロードし適用していただければと思います。
https://github.com/siosio/DomaSupport/releases/download/0.13/DomaSupport.zip

**Comment by tasuku-s** [comment]
ありがとうございます。
エラーが出なくなりました。
